# Import

In [3]:
import numpy as np
import pandas as pd

from pyMSOO.MFEA.model import SM_MFEA
from pyMSOO.utils.Crossover import *
from pyMSOO.utils.Mutation import *
from pyMSOO.utils.Selection import *
from pyMSOO.utils.DimensionAwareStrategy import DaS_strategy

from pyMSOO.utils.EA import * 
from pyMSOO.MFEA.benchmark.continous.CEC17 import CEC17_benchmark 
from pyMSOO.MFEA.benchmark.continous.WCCI22 import WCCI22_benchmark

from pyMSOO.utils.MultiRun.RunMultiTime import * 
from pyMSOO.utils.MultiRun.RunMultiBenchmark import * 

# Run

In [4]:
# tasks, IndClass = CEC17_benchmark.get_2tasks_benchmark(1)
# tasks, IndClass = WCCI22_benchmark.get_complex_benchmark(1)
tasks, IndClass = CEC17_benchmark.get_10tasks_benchmark()

1 time

In [5]:
SM_SBX = SM_MFEA.model()
SM_SBX.compile(
    IndClass= IndClass,
    tasks= tasks,
    crossover= SBX_Crossover(nc = 2),
    mutation= PolynomialMutation(nm = 5),
)
solve = SM_SBX.fit(
    nb_generations= 1000, nb_inds_each_task= 100, nb_inds_min= 20,
    lr = 0.1, mu=0.1,
    evaluate_initial_skillFactor= True
)

Seed: None -- Time: 01m 1.11s  100 % [====================>]  Pop_size: 1.90E+02  ,  Cost: 3.17E-26  2.91E-26  0.00E+00  0.00E+00  4.71E+01  4.66E-14  0.00E+00  3.61E+03  0.00E+00  2.29E+01  ,  
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[100186, 99830, 100086, 100426, 99258, 100392, 99936, 100036, 100104, 99776]
END!


In [6]:
SM_KL_SBX = SM_MFEA.model()
SM_KL_SBX.compile(
    IndClass= IndClass,
    tasks= tasks,
    crossover= DaS_SBX_Crossover(nc = 2),
    mutation= PolynomialMutation(nm = 5),
)
solve = SM_KL_SBX.fit(
    nb_generations= 1000, nb_inds_each_task= 100, nb_inds_min= 20,
    lr = 0.1, mu=0.1,
    evaluate_initial_skillFactor= True
)

Seed: None -- Time: 01m 5.41s  100 % [====================>]  Pop_size: 1.90E+02  ,  Cost: 7.92E-22  1.62E-26  0.00E+00  0.00E+00  3.16E-12  4.66E-14  0.00E+00  6.36E-04  0.00E+00  0.00E+00  ,  
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[99410, 100600, 100286, 99782, 99918, 99838, 100090, 99686, 100082, 100338]
END!


In [6]:
SM_KL_SBX.crossover.prob[9][1]

array([0.91604249, 0.91256795, 0.98857103, 0.98516035, 0.90975089,
       0.02      , 0.98846469, 0.02      , 0.91484108, 0.98705149,
       0.98765445, 0.99364588, 0.98835255, 0.90767182, 0.9122587 ,
       0.98786872, 0.02      , 0.91195157, 0.98551478, 0.9144308 ,
       0.98633307, 0.91234604, 0.91421428, 0.91185109, 0.91353229,
       0.02      , 0.02      , 0.02      , 0.02      , 0.02      ,
       0.02      , 0.02      , 0.02      , 0.02      , 0.02      ,
       0.02      , 0.02      , 0.02      , 0.02      , 0.02      ,
       0.02      , 0.02      , 0.02      , 0.02      , 0.02      ,
       0.02      , 0.02      , 0.02      , 0.02      , 0.02      ])

In [4]:
SM_DaS = SM_MFEA.model()
SM_DaS.compile(
    IndClass= IndClass,
    tasks= tasks,
    crossover= SBX_Crossover(nc = 2),
    mutation= PolynomialMutation(nm = 5),
    dimension_strategy= DaS_strategy(eta= 3)
)
solve = SM_DaS.fit(
    nb_generations= 1000, nb_inds_each_task= 100, nb_inds_min= 20,
    lr = 0.1, mu=0.1,
    evaluate_initial_skillFactor= True
)

Seed: None -- Time: 01m 27.88s  100 % [====================>]  Pop_size: 1.90E+02  ,  Cost: 3.78E-26  2.10E-26  0.00E+00  0.00E+00  3.44E-18  4.31E-14  0.00E+00  6.36E-04  0.00E+00  0.00E+00  ,  
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[101250, 99582, 100268, 99958, 100364, 99826, 99378, 99214, 99756, 100434]
END!
