# Import

In [1]:
import numpy as np
import pandas as pd

from pyMSOO.MFEA.model import SM_MFEA
from pyMSOO.utils.Crossover import *
from pyMSOO.utils.Mutation import *
from pyMSOO.utils.Selection import *
from pyMSOO.utils.DimensionAwareStrategy import DaS_strategy

from pyMSOO.utils.EA import * 
from pyMSOO.MFEA.benchmark.continous.CEC17 import CEC17_benchmark 
from pyMSOO.MFEA.benchmark.continous.WCCI22 import WCCI22_benchmark

from pyMSOO.utils.MultiRun.RunMultiTime import * 
from pyMSOO.utils.MultiRun.RunMultiBenchmark import * 

# Run

In [2]:
# tasks, IndClass = CEC17_benchmark.get_2tasks_benchmark(1)
# tasks, IndClass = WCCI22_benchmark.get_complex_benchmark(1)
tasks, IndClass = CEC17_benchmark.get_10tasks_benchmark()

1 time

In [3]:
SM_SBX = SM_MFEA.model()
SM_SBX.compile(
    IndClass= IndClass,
    tasks= tasks,
    crossover= SBX_Crossover(nc = 2),
    mutation= PolynomialMutation(nm = 5),
)
solve = SM_SBX.fit(
    nb_generations= 1000, nb_inds_each_task= 100, nb_inds_min= 20,
    lr = 0.1, mu=0.1,
    evaluate_initial_skillFactor= True
)

Seed: None -- Time: 01m 43.66s  100 % [====================>]  Pop_size: 1.90E+02  ,  Cost: 2.89E-26  2.67E-26  0.00E+00  0.00E+00  2.93E-24  4.31E-14  0.00E+00  3.12E+03  7.40E-03  2.29E+01  ,  
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[99664, 100644, 99916, 100062, 100524, 99288, 100066, 99558, 100012, 100296]
END!


In [5]:
SM_KL_SBX = SM_MFEA.model()
SM_KL_SBX.compile(
    IndClass= IndClass,
    tasks= tasks,
    crossover= DaS_SBX_Crossover(nc = 2),
    mutation= PolynomialMutation(nm = 5),
)
solve = SM_KL_SBX.fit(
    nb_generations= 1000, nb_inds_each_task= 100, nb_inds_min= 20,
    lr = 0.1, mu=0.1,
    evaluate_initial_skillFactor= True
)

Seed: None -- Time: 01m 49.55s  100 % [====================>]  Pop_size: 1.90E+02  ,  Cost: 1.84E-26  1.45E-26  0.00E+00  0.00E+00  1.24E-24  4.31E-14  0.00E+00  6.36E-04  0.00E+00  0.00E+00  ,  
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[100700, 99916, 99812, 99510, 99306, 100632, 99230, 99848, 100890, 100186]
END!


In [6]:
SM_KL_SBX.crossover.prob[9][1]

array([0.91604249, 0.91256795, 0.98857103, 0.98516035, 0.90975089,
       0.02      , 0.98846469, 0.02      , 0.91484108, 0.98705149,
       0.98765445, 0.99364588, 0.98835255, 0.90767182, 0.9122587 ,
       0.98786872, 0.02      , 0.91195157, 0.98551478, 0.9144308 ,
       0.98633307, 0.91234604, 0.91421428, 0.91185109, 0.91353229,
       0.02      , 0.02      , 0.02      , 0.02      , 0.02      ,
       0.02      , 0.02      , 0.02      , 0.02      , 0.02      ,
       0.02      , 0.02      , 0.02      , 0.02      , 0.02      ,
       0.02      , 0.02      , 0.02      , 0.02      , 0.02      ,
       0.02      , 0.02      , 0.02      , 0.02      , 0.02      ])

In [3]:
SM_DaS = SM_MFEA.model()
SM_DaS.compile(
    IndClass= IndClass,
    tasks= tasks,
    crossover= SBX_Crossover(nc = 2),
    mutation= PolynomialMutation(nm = 5),
    dimension_strategy= DaS_strategy(eta= 3)
)
solve = SM_DaS.fit(
    nb_generations= 1000, nb_inds_each_task= 100, nb_inds_min= 20,
    lr = 0.1, mu=0.1,
    evaluate_initial_skillFactor= True
)

Seed: None -- Time: 01m 51.10s  100 % [====================>]  Pop_size: 1.90E+02  ,  Cost: 1.74E-26  3.55E-26  0.00E+00  0.00E+00  1.09E-24  5.02E-14  0.00E+00  6.36E-04  0.00E+00  0.00E+00  ,  
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[99852, 100540, 99826, 99210, 99790, 100062, 99576, 100608, 99664, 100902]
END!
