In [1]:
from pyMSOO.MFEA.benchmark.continous.CEC17 import CEC17_benchmark 
from pyMSOO.MFEA.benchmark.continous.WCCI22 import WCCI22_benchmark
import numpy as np 

In [3]:
'''Khởi tạo tác vụ '''
tasks, IndClass = CEC17_benchmark.get_10tasks_benchmark()
tasks, IndClass = WCCI22_benchmark.get_complex_benchmark(ID= 1)
tasks, IndClass = WCCI22_benchmark.get_50tasks_benchmark(ID= 1)

In [4]:
'''Xem chi tiết '''
tasks

In [2]:
import numpy as np 

a = [1,2,3,4,5]
print(type(a))
a = np.array(a)
print(type(a))
x = np.random.rand(50) 
print(type(x))

<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [5]:
'''Khởi tạo giá trị của x và đánh giá'''
x = np.random.rand(50) 
tasks[0](x) # thực hiện đánh giá hàm 

687.0676693667924

In [14]:
with open("./text.txt", 'r') as file: 
    data = file.readline()

data = data.split(" ")
data = np.array(data, dtype= np.float64)

In [15]:
print(type(data[0]))

<class 'numpy.float32'>


In [8]:
x = np.array([0.1,0.2, 0.5,0.2, 0.55, 0.95, 0.14, 0.4, 0.5,0.78], dtype= np.float32)
x_de = x * (50 + 50) + -50 

In [9]:
print(x_de)

[-40. -30.   0. -30.   5.  45. -36. -10.   0.  28.]


In [12]:
gene_pa = np.array([0.1,0.2, 0.5,0.2, 0.55, 0.95, 0.14, 0.4, 0.5,0.78], dtype= np.float32)
gene_pb = np.array([0.2,0.3, 0.2,0.6, 0.7, 0.5, 0.6, 0.15, 0.6,0.9], dtype= np.float32)

def crossover(gene_pa, gene_pb):
    nc = 2 
    u = np.random.rand(10)
    beta = np.where(u < 0.5, (2*u)**(1/(nc +1)), (2 * (1 - u))**(-1 / (nc + 1)))

    #like pa
    gene_oa = np.clip(0.5*((1 + beta) * gene_pa + (1 - beta) * gene_pb), 0, 1)
    #like pb
    gene_ob = np.clip(0.5*((1 - beta) * gene_pa + (1 + beta) * gene_pb), 0, 1)
    return gene_oa, gene_ob


In [9]:
def mutation(genes):
    pm = 1 / 10
    nm = 5 
    idx_mutation = np.where(np.random.rand(10) <= pm)[0]

    u = np.zeros((10,)) + 0.5
    u[idx_mutation] = np.random.rand(len(idx_mutation))

    delta = np.where(u < 0.5,
        # delta_l
        (2*u)**(1/(nm + 1)) - 1,
        # delta_r
        1 - (2*(1-u))**(1/(nm + 1))
    )


    return np.where(delta < 0,
                        # delta_l: ind -> 0
                        # = genes * (delta + 1)
                        genes + delta * genes,
                        # delta_r: ind -> 1
                        # = genes (1 - delta) + delta
                        genes + delta * (1 - genes)
                    )
    
def _func(x):
    x = x * 100 - 50 
    l = 100*np.sum((x[1:] - x[:-1]**2) ** 2)
    r = np.sum((x[:-1] - 1) ** 2)
    return l + r

In [18]:
x = np.load("./random_x.npy")
off = [] 
while len(off) < len(x):
    idx1, idx2, idx3, idx4 = np.random.choice(len(x), size= 4, replace= False)
    idx1 = idx1 if _func(x[idx1]) < _func(x[idx2]) else idx2
    idx3 = idx3 if _func(x[idx3]) < _func(x[idx4]) else idx4
    if np.random.rand() < 0.7:
        oa, ob = crossover(x[idx1], x[idx3])
    else: 
        oa = mutation(np.copy(x[idx1]))
        ob = mutation(np.copy(x[idx3]))
    off.append(np.copy(oa))
    off.append(np.copy(ob))

In [19]:
off = np.array(off)
x = np.concatenate([x, off], axis= 0)
for i in x: 
    print(np.round(i, 2))

[0.1  0.2  0.5  0.2  0.55 0.95 0.14 0.4  0.5  0.78]
[0.08 0.43 0.95 0.84 0.73 0.96 0.53 0.95 0.15 0.07]
[0.57 0.94 0.46 0.87 0.23 0.33 0.93 0.34 0.02 0.2 ]
[0.29 0.16 0.78 0.03 0.88 0.2  0.13 0.64 0.16 0.49]
[0.29 0.28 0.97 0.01 0.55 0.67 0.64 0.45 0.91 0.56]
[0.8  0.66 0.33 0.45 0.91 0.64 0.05 0.4  0.32 0.73]
[0.76 0.76 0.27 0.91 0.85 0.5  0.68 0.09 0.51 0.29]
[0.87 0.65 0.77 0.52 0.57 0.75 0.12 0.76 0.55 0.08]
[0.72 0.68 0.31 0.3  0.2  0.96 0.53 0.15 0.69 0.93]
[0.63 0.18 0.79 0.26 0.15 0.17 0.03 0.69 0.07 0.77]
[0.8  0.66 0.33 0.45 0.91 0.64 0.05 0.4  0.32 0.73]
[0.29 0.16 0.78 0.03 0.68 0.2  0.13 0.64 0.16 0.49]
[0.76 0.76 0.27 0.91 0.85 0.5  0.58 0.1  0.51 0.29]
[0.85 0.67 0.77 0.52 0.57 0.75 0.12 0.76 0.55 0.08]
[0.94 0.66 0.66 0.57 0.63 0.91 0.   0.65 0.55 0.03]
[0.69 0.76 0.38 0.86 0.8  0.34 1.   0.19 0.51 0.35]
[0.8  0.66 0.33 0.45 0.91 0.64 0.05 0.4  0.32 0.73]
[0.76 0.76 0.27 0.92 0.85 0.5  0.68 0.09 0.51 0.29]
[0.38 0.11 0.85 0.03 0.88 0.24 0.29 0.52 0.16 0.51]
[0.67 0.81 0

In [39]:
argsort = np.argsort([_func(i) for i in x])

In [1]:
for i in range(1,11):
    print(f"Cá thể c_{i}")

Cá thể c_1
Cá thể c_2
Cá thể c_3
Cá thể c_4
Cá thể c_5
Cá thể c_6
Cá thể c_7
Cá thể c_8
Cá thể c_9
Cá thể c_10


In [44]:
argsort2 = np.argsort(argsort)

In [42]:
print(argsort)

[13  7 19  8 12 10 16  5  6 17  0 15 11 14 18  3  9  4  2  1]


In [41]:
a = np.array([_func(i) for i in x])[argsort]

In [38]:
print(a)

[4.83069544e+08 5.13979153e+08 7.01109841e+08 7.50171078e+08
 8.08612943e+08 8.14919435e+08 8.21583788e+08 8.21583788e+08
 8.46863882e+08 8.68629126e+08 1.02334359e+09 1.03115366e+09
 1.10763687e+09 1.29098554e+09 1.29290980e+09 1.30873735e+09
 1.32164537e+09 1.40940086e+09 1.51811629e+09 1.86868686e+09]


In [28]:
for i in range(1,11):
    print(f'c_{i}')

c_1
c_2
c_3
c_4
c_5
c_6
c_7
c_8
c_9
c_10


In [36]:
for i in x: 
    print("%.2E" %_func(i))

1.02E+09
1.87E+09
1.52E+09
1.31E+09
1.41E+09
8.22E+08
8.47E+08
5.14E+08
7.50E+08
1.32E+09
8.15E+08
1.11E+09
8.09E+08
4.83E+08
1.29E+09
1.03E+09
8.22E+08
8.69E+08
1.29E+09
7.01E+08


In [45]:
for i in argsort2: 
    print(i+1)

11
20
19
16
18
8
9
2
4
17
6
13
5
1
14
12
7
10
15
3


In [21]:
x = np.random.rand(10, 10)
x[0] = np.array([0.1,0.2, 0.5,0.2, 0.55, 0.95, 0.14, 0.4, 0.5,0.78], dtype= np.float32)
for index,i in enumerate(x): 
    print(f'Cá thể x_{index + 1}: ', np.round(i, 2).tolist())

Cá thể x_1:  [0.1, 0.2, 0.5, 0.2, 0.55, 0.95, 0.14, 0.4, 0.5, 0.78]
Cá thể x_2:  [0.08, 0.43, 0.95, 0.84, 0.73, 0.96, 0.53, 0.95, 0.15, 0.07]
Cá thể x_3:  [0.57, 0.94, 0.46, 0.87, 0.23, 0.33, 0.93, 0.34, 0.02, 0.2]
Cá thể x_4:  [0.29, 0.16, 0.78, 0.03, 0.88, 0.2, 0.13, 0.64, 0.16, 0.49]
Cá thể x_5:  [0.29, 0.28, 0.97, 0.01, 0.55, 0.67, 0.64, 0.45, 0.91, 0.56]
Cá thể x_6:  [0.8, 0.66, 0.33, 0.45, 0.91, 0.64, 0.05, 0.4, 0.32, 0.73]
Cá thể x_7:  [0.76, 0.76, 0.27, 0.91, 0.85, 0.5, 0.68, 0.09, 0.51, 0.29]
Cá thể x_8:  [0.87, 0.65, 0.77, 0.52, 0.57, 0.75, 0.12, 0.76, 0.55, 0.08]
Cá thể x_9:  [0.72, 0.68, 0.31, 0.3, 0.2, 0.96, 0.53, 0.15, 0.69, 0.93]
Cá thể x_10:  [0.63, 0.18, 0.79, 0.26, 0.15, 0.17, 0.03, 0.69, 0.07, 0.77]


In [25]:
np.save('random_x.npy', x)

In [24]:


def _func(x):
    l = 100*np.sum((x[1:] - x[:-1]**2) ** 2)
    r = np.sum((x[:-1] - 1) ** 2)
    return l + r

In [23]:
1023343590.55 - 1.02e9

3343590.5499999523

In [22]:
for i in x: 
    print(_func(i * 100 - 50))

1023343590.5495087
1868686858.9524992
1518116286.4742084
1308737351.5823112
1409400855.0349855
821583787.9332201
846863881.8929383
513979152.92018116
750171078.2564496
1321645372.2871668


In [20]:
x_de

array([-40., -30.,   0., -30.,   5.,  45., -36., -10.,   0.,  28.],
      dtype=float32)

In [ ]:
x = [
    [0.49700407 0.49866642 0.49952277 0.50276777 0.50285304 0.50331323
  0.50631092 0.50705511 0.51033615 0.5393445 ],
  [0.49700407 0.49866642 0.49952277 0.50276777 0.50285304 0.50331323
  0.50631092 0.50705511 0.51033615 0.5393445 ],
  [0.49700407 0.49866642 0.49952277 0.50276777 0.50285304 0.50331323
  0.50631092 0.50705511 0.51033615 0.5393445 ],
  [0.49700407 0.49866642 0.49952277 0.50276777 0.50285304 0.50331323
  0.50631092 0.50705511 0.51033615 0.5393445 ],
  [0.49700407 0.49866642 0.49952277 0.50276777 0.50285304 0.50331323
  0.50631092 0.50705511 0.51033615 0.5393445 ],
  [0.49700407 0.49866642 0.49952277 0.50276777 0.50285304 0.50331323
  0.50631092 0.50705511 0.51033615 0.5393445 ],
  

]